### ISSUE TITLE
please add support for 1.3.~ angular

### ISSUE THREAD

**Issue by tlimpanont** [fvanwijk/mox#1]
Does the lib support 1.3.~ of angular and angular-mocks?

**Comment by fvanwijk** [comment]
Mox was built for a large project that uses Angular 1.2 and Jasmine 1.x. So it is extensively tested in these versions. 
It is lightly built on top of angular-mocks.

Later Jasmine 2.x and Angular 1.3 support was added, so you should be able to use Mox with your Angular 1.3 projects. However, there are as far as I know not yet any large projects in Angular 1.3 that use Mox, so this is not very well tested in the field. I will update the readme to reflect this information.

If you encounter any issues please create a new issue with a more detailed description and I will fix it. If you have any questions, feel free to ask them.
