### ISSUE TITLE
Examples: Update with promises examples?

### ISSUE THREAD

**Issue by ryananthonydrake** [fvanwijk/mox#13]
I'd love to see examples for how you are testing promises in the README.md?

Thanks!

**Comment by fvanwijk** [comment]
Testing promises something you don't need Mox directly for.
When testing resources using the `requestTest` DSL, Mox tests the promises returned by the resources using [jasmine-mox-matchers](https://github.com/fvanwijk/jasmine-mox-matchers).
You can use these matchers to test your own promises as well.

**Comment by ryananthonydrake** [comment]
True, except you do have promise helpers, so would be good to see example code that uses them!

**Comment by fvanwijk** [comment]
Yes, I will include that in the examples as mentioned in #14 as well, since mocking resources and service methods that return resource results / promises need to be tested too :)
