### ISSUE TITLE
Create example project

### ISSUE THREAD

**Issue by ryananthonydrake** [fvanwijk/mox#14]
[edit-fvanwijk]Warning "/test/moxConfig.js" does not match any file in Karma output[/edit-fvanwijk]

I get the above warning when I'm running Karma.

Where is this file created?

**Comment by ryananthonydrake** [comment]
OK I re-read the README. Makes sense.

However, what I'd love to see is a basic app with code to reference mox accordingly.

I'm still quite confused as to whether or not I include the full usage example in the moxConfig.js file or directly in my tests? And how they're linked up.

**Comment by fvanwijk** [comment]
I'm currently working on an example app that shows several use cases where Mox greatly improves your testing experience. Documentation with example code is also under development.
For now this example - created to demonstrate missing feature #9 - could help you getting started.
https://github.com/fvanwijk/moxCallThroughBugPOC

I improved the readme on the full usage example to prevent confusion.

I agree that the moxConfig part feels a bit unnatural. A config file like karma.conf.js that hooks into the testing pipeline will be better. In that way you can set some future config options.

**Comment by fvanwijk** [comment]
The example project can be found at [fvanwijk/mox-example](https://github.com/fvanwijk/mox-example).
If there is anything missing, please let me know.
