### ISSUE TITLE
Getting Error: Sorry, cannot inject CampaignsService because the injector is not ready yet. Please call mox.run() 

### ISSUE THREAD

**Issue by ryananthonydrake** [fvanwijk/mox#15]
Getting this error in my terminal:
`Error: Sorry, cannot inject CampaignsService because the injector is not ready yet. Please call mox.run() or inject()`

My test block:

```
describe("CampaignsService", function () {
    beforeEach(function () {
        mox.mockServices('CampaignsService');
        mox.run();
    });

    it("should initialize correctly", function () {
        var CampaignsService  = mox.inject('CampaignsService');
        expect(CampaignsService).toBe(mox.get.CampaignsService);
    });
});
```

Any ideas why I'd be getting this error?

**Comment by fvanwijk** [comment]
If you want to inject services in Angular, you have to load a module, just as you would do without Mox. So you have to call `mox.module('myApp').....`. This is the equivalent of `module` or `angular.mock.module`.
The exception message is improved now, see 640b650c4096bbcb0ff475156bbe9232ed7a3c20

Note that you can chain the mox call. It saves you some lines of code.

``` javascript
mox
  .module('myApp')
  .mockServices('CampaignsService')
  .run();
```

Does this solve your problem?

**Comment by fvanwijk** [comment]
I'll close this for now. If you have any issues, please let me know.
