### ISSUE TITLE
mox inject single same behavior as multiple

### ISSUE THREAD

**Issue by RRMoelker** [fvanwijk/mox#6]
The mox inject functionality is really, really, handy. However I would like to have consistent behavior for single and multiple injections. When injecting multiple elements you can access the properties as such:

```
var inj = mox.inject('service1', 'service2');
inj.service2
```

When injecting a single service I would like to use the same syntax, so something along the lines of:

```
var inj = mox.inject('service1');
inj.service1
```

This of course does not work because variable `inj` is the injected service. So I want to suggest and maybe implement another syntax:

```
var inj = mox.inject( ['service1']);
inj.service1
inj = mox.inject( ['service1', 'service2']);
inj.service2
```

Passing an **array** of desired injections creates an object for any number of services. This can be made on top of the current functionality though I would deprecate the old behavior.

**Comment by fvanwijk** [comment]
Actually the behaviour is consistent with `mockControllers`, `mockDirectives` etc.: one or multiple arguments are supported. However, `mox.inject` returns service(s), which is different compared to the other methods.

Most users have to inject one service, namely the service that is tested. It would be overhead when an object is returned with the injected service, while you only need that service. So I would like to leave the implementation as it is.

For example:

``` javascript
// FooService.js
angular.module('myApp').service('FooService', function (service1, service2) {
  // Do something
  return {};
});

// fooServiceSpec.js
var fooService;

beforeEach(function () {

  mox
    .module('myApp')
    .mockServices('service1', 'service2') // Multiple mocks
    .run();

  // This is the only injection, the unit under test
  fooService = mox.inject('FooService');
});
```

Your suggestion is to (additionally?) provide an array argument to instruct 'mox.inject' to return an object. This gives more freedom to the developer, but can be confusing as well. What should `mox.inject('service1', 'service2')` return?

Besides that, providing arrays is inconsistent with the other methods, where array-arguments are deprecated.

When Mox will be fully ES6, [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) is supported, which solves all these issues.

**Comment by RRMoelker** [comment]
Okay, if this behavior is consistent with other methods than it is probably best to leave as is. Providing a secondary way to use the method (using arrays) is confusing.

Looking forward to an ES6 implementation :+1:
